if {[catch {
set f [open {/workspace/pdf-dataflow-sim/results/passthrough-native.csv} w]
puts $f {kind,row,ns,v0,v1,v2,v3,v4,v5,v6,v7,v8,v9,v10,v11,v12,v13}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}}
gtkwave::setMarker 4854999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}]
puts $f "weight,0,4855,[join $vals ,]"
gtkwave::setMarker 4864999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}]
puts $f "weight,1,4865,[join $vals ,]"
gtkwave::setMarker 4874999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}]
puts $f "weight,2,4875,[join $vals ,]"
gtkwave::setMarker 4884999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}]
puts $f "weight,3,4885,[join $vals ,]"
gtkwave::setMarker 4894999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}]
puts $f "weight,4,4895,[join $vals ,]"
gtkwave::setMarker 4904999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}]
puts $f "weight,5,4905,[join $vals ,]"
gtkwave::setMarker 4914999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}]
puts $f "weight,6,4915,[join $vals ,]"
gtkwave::setMarker 4924999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}]
puts $f "weight,7,4925,[join $vals ,]"
gtkwave::setMarker 4934999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}]
puts $f "weight,8,4935,[join $vals ,]"
gtkwave::setMarker 4944999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}]
puts $f "weight,9,4945,[join $vals ,]"
gtkwave::setMarker 4954999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}]
puts $f "weight,10,4955,[join $vals ,]"
gtkwave::setMarker 4964999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}]
puts $f "weight,11,4965,[join $vals ,]"
gtkwave::setMarker 4974999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}]
puts $f "weight,12,4975,[join $vals ,]"
gtkwave::setMarker 4984999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.weight_read_port0[13][7:0]}]
puts $f "weight,13,4985,[join $vals ,]"
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}}
gtkwave::setMarker 5024999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}]
puts $f "mmu,0,5025,[join $vals ,]"
gtkwave::setMarker 5034999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}]
puts $f "mmu,1,5035,[join $vals ,]"
gtkwave::setMarker 5044999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}]
puts $f "mmu,2,5045,[join $vals ,]"
gtkwave::setMarker 5054999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}]
puts $f "mmu,3,5055,[join $vals ,]"
gtkwave::setMarker 5064999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}]
puts $f "mmu,4,5065,[join $vals ,]"
gtkwave::setMarker 5074999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}]
puts $f "mmu,5,5075,[join $vals ,]"
gtkwave::setMarker 5084999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}]
puts $f "mmu,6,5085,[join $vals ,]"
gtkwave::setMarker 5094999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}]
puts $f "mmu,7,5095,[join $vals ,]"
gtkwave::setMarker 5104999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}]
puts $f "mmu,8,5105,[join $vals ,]"
gtkwave::setMarker 5114999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}]
puts $f "mmu,9,5115,[join $vals ,]"
gtkwave::setMarker 5124999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}]
puts $f "mmu,10,5125,[join $vals ,]"
gtkwave::setMarker 5134999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}]
puts $f "mmu,11,5135,[join $vals ,]"
gtkwave::setMarker 5144999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}]
puts $f "mmu,12,5145,[join $vals ,]"
gtkwave::setMarker 5154999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[0][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[1][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[2][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[3][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[4][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[5][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[6][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[7][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[8][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[9][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[10][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[11][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[12][31:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.mmu_result_data[13][31:0]}]
puts $f "mmu,13,5155,[join $vals ,]"
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}}
if {[gtkwave::addSignalsFromList [list {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}]] != 1} {error {Missing top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}}
gtkwave::setMarker 5304999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}]
puts $f "activation,0,5305,[join $vals ,]"
gtkwave::setMarker 5314999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}]
puts $f "activation,1,5315,[join $vals ,]"
gtkwave::setMarker 5324999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}]
puts $f "activation,2,5325,[join $vals ,]"
gtkwave::setMarker 5334999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}]
puts $f "activation,3,5335,[join $vals ,]"
gtkwave::setMarker 5344999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}]
puts $f "activation,4,5345,[join $vals ,]"
gtkwave::setMarker 5354999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}]
puts $f "activation,5,5355,[join $vals ,]"
gtkwave::setMarker 5364999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}]
puts $f "activation,6,5365,[join $vals ,]"
gtkwave::setMarker 5374999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}]
puts $f "activation,7,5375,[join $vals ,]"
gtkwave::setMarker 5384999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}]
puts $f "activation,8,5385,[join $vals ,]"
gtkwave::setMarker 5394999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}]
puts $f "activation,9,5395,[join $vals ,]"
gtkwave::setMarker 5404999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}]
puts $f "activation,10,5405,[join $vals ,]"
gtkwave::setMarker 5414999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}]
puts $f "activation,11,5415,[join $vals ,]"
gtkwave::setMarker 5424999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}]
puts $f "activation,12,5425,[join $vals ,]"
gtkwave::setMarker 5434999999
set vals [list]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[0][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[1][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[2][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[3][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[4][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[5][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[6][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[7][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[8][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[9][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[10][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[11][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[12][7:0]}]
lappend vals [gtkwave::getTraceValueAtMarkerFromName {top.tb_pdf_dataflow.dut_i.tpu_i.tpu_core_i.buffer_write_port1[13][7:0]}]
puts $f "activation,13,5435,[join $vals ,]"
close $f

} err]} {puts "TCL_ERROR: $err"}
gtkwave::/File/Quit
